hw3
Headhunter1223/homeworks pull request #1
Opened 2021-05-17 07:20 UTC by Headhunter1223

2021-05-25 22:01 UTC, ValeryStatinov requested changes

2021-05-25 22:01 UTC, ValeryStatinov commented on src/App.js
> +          <button />
по клику на кнопку ничего не происходит, а должно выводиться сообщение в консоль

2021-05-27 15:27 UTC, Headhunter1223 commented on src/App.js
> +          <button />
Получается нужно,
<button onClick= () => {
console.log('объект:', this);
}/>

2021-05-27 17:56 UTC, ValeryStatinov commented on src/App.js
> +          <button />
да, почти. только не this

по заданию посмотри какую строку надо выводить

2021-06-05 15:59 UTC, merged