hw4  Чистяков Игорь. Пришлось сильно переписать код((( Но ничего получилось
Headhunter1223/homeworks pull request #2
Opened 2021-05-17 12:44 UTC by Headhunter1223

2021-05-25 22:09 UTC, ValeryStatinov requested changes

2021-05-25 22:09 UTC, ValeryStatinov commented on src/App.js
> +    item.completed = !item.completed;
это мутация стейта:( spread operator делаеть shallow copy. то есть `stateCopy === this.state // false`, но при этом `stateCopy.todos === this.state.todos // true`

2021-05-25 22:09 UTC, ValeryStatinov commented on src/App.js
> +    e.preventDefault();
почему понадобился `e.preventDefault()` и что вообще делает этот вызов?

2021-05-25 22:09 UTC, ValeryStatinov commented on src/App.js
> +  };
по финкционалу кажется, что эта ф-ия пытается делать что-то очень похожее на `toggleComplete`. зачем две ф-ии?

2021-05-27 15:24 UTC, Headhunter1223 commented on src/App.js
> +    item.completed = !item.completed;
toggleComplete = (todoItem) => {
this.setState(() => {
todoItem.completed = !todoItem.completed;
return { completed: !todoItem.completed };
});
};
Вот так надо было?

2021-05-27 15:25 UTC, Headhunter1223 commented on src/App.js
> +  };
функция ставит все таски невыполненными

2021-05-27 15:26 UTC, Headhunter1223 commented on src/App.js
> +    e.preventDefault();
Потому что в React нельзя предотвратить обработчик события по умолчанию, вернув false. Нужно явно вызвать preventDefault, это я нашел на reactjs.org, поэтому и вставил

2021-06-02 09:43 UTC, ValeryStatinov commented on src/App.js
> +    item.completed = !item.completed;
нет, не так( посмотри в примерах с семинаров, как нужно менять стейт без мутаций

2021-06-22 10:41 UTC, closed without merging